_BASE_: "../Base-CenterNet.yaml"
MODEL:
  WEIGHTS: "/projects/sgt_output/mot17_val/dla34_mot17-CenterNet/centernet_dla34_coco.pth"
  BACKBONE:
    NAME: "DLA"
  CENTERNET:
    UPSAMPLE_LAYER:
      NAME: "DLASegUp"
    NUM_CLASSES: 1
    OUTPUT_SIZE: (608, 1088)
    HM_SIZE: (152, 272)
    INPUT_ALIGN: False
    MAX_PER_IMAGE: 100
DATASETS:
  TRAIN: ("mix_mot17_sub_train",)
  TEST: ("mot17_sub_val",)
DATALOADER:
  SAMPLER_TEST: "InfInferenceSampler"
  NUM_SAMPLES_TEST: 1
  FILTER_EMPTY_ANNOTATIONS: True
  SEED: 1234
SOLVER:
  OPTIMIZER: "Adam"
  IMS_PER_BATCH: 10
  BASE_LR: 0.0001
  STEPS: (20, )
  WARMUP_ITERS: 0
  MAX_EPOCH: 1 #30
  CHECKPOINT_PERIOD: 5
TEST:
  EVAL_PERIOD: 30
  EVAL_DETECTION: True
  EVAL_TRACKING: False